apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: environments-appset
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - scmProvider:
        github:
          organization: initech-ai
          allBranches: true
          tokenRef:
            secretName: github-token
            key: token
        filters:
          - repositoryMatch: "Initech-config"
            branchMatch: "^env/.*"
  template:
    metadata:
      name: 'root-{{ .branch | replace "/" "-" }}'
    spec:
      project: default
      source:
        repoURL: '{{ .url }}'
        targetRevision: '{{ .branch }}'
        path: apps-rendered
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
