apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: environments-appset
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/therealdavidbour/Initech-config.git
        revision: HEAD
        directories:
          - path: environments/*/*
  template:
    metadata:
      name: '{{path[1]}}-{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/therealdavidbour/Initech-config.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path[1]}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
