apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: orders-api-{{ .Values.branch | replace "/" "-" }}
  namespace: argocd
spec:
  project: default
  source:
    repoURL: {{ .Values.repoURL }}
    targetRevision: {{ .Values.branch }}
    path: services/orders-api/templates
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.branch | replace "/" "-" }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
