apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-app-2
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-app-2
  template:
    metadata:
      labels:
        app: example-app-2
    spec:
      containers:
        - name: example-app-2
          image: nginx:alpine
          ports:
            - containerPort: 80
