apiVersion: apps/v1
kind: Deployment
metadata:
  name: recipe-api
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recipe-api
  template:
    metadata:
      labels:
        app: recipe-api
    spec:
      containers:
        - name: recipe-api
          image: ghcr.io/therealdavidbour/recipe-api:0f2e1e99c1b92f6af59c610f006263604cd5db12
          ports:
            - containerPort: 8000
