apiVersion: apps/v1
kind: Deployment
metadata:
  name: recipe-api
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recipe-api
  template:
    metadata:
      labels:
        app: recipe-api
    spec:
      containers:
        - name: recipe-api
          image: ghcr.io/therealdavidbour/recipe-api:latest
          ports:
            - containerPort: 8000
