apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: recipe-api
  namespace: dev
spec:
  ingressClassName: nginx
  rules:
    - host: recipe-api.10-0-0-200.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: recipe-api
                port:
                  number: 80
